cache: yarn
language: node_js
node_js:
  - 'node'
  - '8'
os: linux
stages:
  - name: deploy
    if: (branch = "master" OR branch = "master-lts") AND type != pull_request AND tag IS blank
jobs:
  include:
  - stage: deploy
    script:
    - yarn run travis-ssh
    - git remote set-url origin git@github.com:nativecode-dev/native.git
    - git checkout $TRAVIS_BRANCH
    - npm set //registry.npmjs.org/:_authToken "$NPM_TOKEN"
    - yarn run push
after_failure:
  - cat lerna-debug.log
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
env:
  global:
  - secure: j9qGqAIT1k6sANqJku9+lv0M/IDbfTmz5D4UyJuRzdeA6wwTDo18w4lSpyLVsaKnXXDtJFRVBRgRQ2KsKUMvrCjYQYVSOStpXgU1ekc2f+P589AFIC+xs2Jp/em49yLnhF4fZFnsDvJKYI2E7c+YUiT/wa9VYiUFaH96z2BkgVIw1PupJqeXfsyLs38EALhz5DzQRu2U8MOA6rJ2Ymo/GLIlmtiZThbBQ9m6DEPp9hYOy0MhzS0KlO1NOkHW/+ddPXBBZwVokpGLYG20MHJ9KdX6Pvubm1dr8dtz7A2R3wIjI3Vt54eXmCfkSqDeRuRJovFCsy8lf6bJrN8jmL50VYrtHvYbXI5dmHvCBxwOt/0AbtQjkM+Qd3qiJn1ndgji/sgnsqx1LB5kb8JjeiYKvpmsHD9Q/nfbQJ2cY9olFclHdAvbIF3a+6wofZlCXHvCGtnXDutXCabY7tkHaQZ5TDGGvnYML7K+FhitpTlizjptMXPaHHYHtXAzVWgGT1jUW8FdTeWKRzmnRyLodKWpQlR5uwpp3IdMuArEhNCxF/qFezkc8qrwmAffmRXoR+RN8a65HV4nka2B/UBaAWvEwnD9RlxwzvStpcKM4cbQvRqMuxsENMJ+r99DK3S5gLDAI5Yfsl7OY3qKAE1Mcm4x7Px8st4x0rtHnsbDs9fifsM=
  - secure: o88GA45I7Di8drffcb+0HBA4n3TFm8B79uJqOHHIjfeAfpqwhFMnnEFLLVKlZ1MxhjO9ulnCn5CvNcTxHwuJRaO90Ry09vVxQiaXmO97jvN9oYl/zjlGtmHZ7IspinrknXM6Hjbdt/grQ8LbT/m5Sw2ItvntCq0H3lIGi45jvzt9AOEnqsgmz7U2FGoDEoYpncz6AEKalxnsuudQKn3c5v4OeL3AKrsf1gy27bNbQS4Uo1U8ks0jLI3nSbTJWAVXuxZUehepSQExK8F+byudoZFC3wbUV3kBr/xPUuyOMMjJ2km4gVvfmujZaReiuiM+8DMjr1dktrUJNpKkqzf0YOEN+ol+Kbr954UX8f50lXoGCeY1xcsZVsfUnPvDctNpf9b/vpv22kqVjwSnxRia8d8VAMR8uezwcBtAeO0RNj+Z3Puur2+XdaoBYwDu5GaGdL+2Cbdku4N0PNwDMYXmWNZqXplUJs4VpMjBsGNX+2SlXjGgEf4TfnxbI6yhj4kv9SdrWP827iX1i/70J691EtY5tA8ErkQPI6VqUO3o1QkFfU+NJfxUcbaMvX+81suCSGNgKfjQTxB8Ny06X8p9GNGDSQ9tekQ5WGWknpagj2Qf+x2r+7WLzTBuaNjZ+P+JpiKzIja0roL5e6UhLqFkMuA+zzq0oNCIvvYdk5PDHN0=
